#!/bin/python3.8

import sys
from PyQt5.QtWidgets import QApplication
from harvesters_gui.frontend.pyqt5 import Harvester

if __name__ == '__main__':
    app = QApplication(sys.argv)
    h = Harvester()
    #h.add_file('/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti')
    #h.update()
    h.show()
    sys.exit(app.exec_())
